### ISSUE TITLE
Long titles don't fit accordingly

### ISSUE THREAD

**Issue by jcfranco** [Esri/reveal.js#11]
Some sessions have really long titles don't look great. We could chop the title to make it fit better, but I think the agenda's title should be honored. I know we can override the CSS, but it's a bit cumbersome if you have to do it for multiple presentations.

<img width="1429" alt="Screen Shot 2019-03-08 at 11 49 18 AM" src="https://user-images.githubusercontent.com/197440/54052162-90b31280-4198-11e9-8eda-c9c85600d305.png">

**Comment by jgravois** [comment]
agreed. and this is true for markdown in _any_ slide.

```md
# much too much big text to fix on a 1080px screen
```
figuring out a way to wrap automatically would be a **big** improvement.

**Comment by gavinr** [comment]
I had the same issue this year. Perhaps a simple css 50% width rule might solve the problem?

**Comment by gavinr** [comment]
Added a note on how presenters can reduce the size of the title in https://github.com/Esri/reveal.js/pull/14/files#diff-6f38e663796746570a7999aacb5b72d2R48.
