### ISSUE TITLE
Support using this repository in a submodule

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/reveal.js#25]
In preparation for Esri Developer Summit, I have a monorepo containing reveal.js html files for several sessions.
To deduplicate the files, I checked out this repository as a submodule in a monorepo.

I am able to "hack" gulp to be run from the submodule, but serve files outside the submodule
```sh
cd reveal.js && npx gulp --cwd ../ --gulpfile ./gulpfile.js serve
```

However, the hot-reloading does not work correctly because the serve task is only watching for direct .html and .md children:

https://github.com/Esri/reveal.js/blob/9369fba36a058840229f6938f39e529c620f60f3/gulpfile.js#L301

## Solutions

- Would it be possible to change that line to something like `gulp.watch(['**/*.html', '**/*.md', '!node_modules/**'], gulp.series('reload'))` to watch subdirectories too?
- Alternatively, can you export the gulp "serve" and "reload" tasks so that I can have a separate gulfile, with gulp.watch in it, which would call the "reload" task when appropriate? (documentation on exporting gulp tasks: https://gulpjs.com/docs/en/getting-started/creating-tasks/#exporting)

**Comment by gavinr-maps** [comment]
> Would it be possible to change that line to something like gulp.watch(['**/*.html', '**/*.md', '!node_modules/**'], gulp.series('reload')) to watch subdirectories too?

@maxpatiiuk I just updated to the latest version of reveal.js which uses that format, so I think this might be solved now. Can you please test with the latest? Thanks!

**Comment by maxpatiiuk** [comment]
Thanks

The gulpfile is now correctly watching for changes, and triggers gulp reload task, but gulp reload task fails:

`Error: File not found with singular glob: /Users/mak13180/site/esri/esri-dev-summit-presentations/index.html`

Fortunately, the fix is simple. See opened PR -
